@startuml

title 입출고 관리 - 입고

legend
  입고지는 외부/내부 으로 선택
endlegend

actor "입고 요청자"

actor "입출고 관리자"

actor "작업자"

entity "입고지"

"입고 요청자" -> "입출고 관리자" : 입고 요청
note left
  입고 요청서는 아래와 같이 구성된다
  - 품목/수량 목록
  - 입고지
    - 외부 - 업체 입고/외주 공정
    - 내부 - 작업 자재 및 완성품 수령
  - 입고요청일시
end note

"입출고 관리자" -> "입출고 관리자" : 입고 Zone + Section 지정

alt 외부 입고

  "입출고 관리자" -> "입출고 관리자" : 운송 선택
  note right
    운송 선택은 운송 사업자를 선택하거나 하지 않음을 의미
  end note
  "입출고 관리자" -> "작업자" : 인수증 발급

  "입출고 관리자" -> "작업자" : 외부 입고 지시
  note right
    외부 입고 지시서는 아래와 같이 구성 된다
    - 품목/수량 목록
    - 입고지
    - 입고요청일시
  end note

  loop 입고 완료시 까지
    "작업자" -> "작업자" : NFC 팔레트 에 입고된 팔레트를 적재
    "작업자" -> "입고지" : 입고
      note right
        입고 팔레트 NFC 태깅하여 품목 및 수량 지정
        입고지 NFC 태깅하여 입고 처리
      end note
  end

  else 내부 입고
    "입출고 관리자" -> "작업자" : 내부 입고 지시
    note right
      내부 입고 지시서는 아래와 같이 구성 된다
      - 팔레트(품목/수량) 목록
      - 입고지
      - 입고요청일시
    end note

    loop 입고 완료시 까지
      "작업자" -> "입고지" : 입고
        note right
          출고지에서 팔레트 NFC 태깅하여 팔레트 선택
          입고지 NFC 태깅하여 입고 처리
        end note
    end
end

"작업자" -> "입출고 관리자" : 입고완료 통보

alt 외부 입고
  "입출고 관리자" -> "입고 요청자" : 인수증 확인 및 전송
  note right
    수령한 인수증은 확인 후 사진촬영하여 시스템에 저장
  end note
  "입출고 관리자" -> "입출고 관리자" : 운송 금액 입력

else 내부 입고
  "입출고 관리자" -> "입고 요청자" : 입고 완료 통보
end

"입출고 관리자" -> "입출고 관리자" : 입고 완료

@enduml
