@startuml
|생산|
start
:외주요청;
|구매|
:외주요청접수;
:발주;
:외주출고요청;
|창고|
:외주출고요청접수;
:배차;
:출고;
|외주사|
:자재인수;
|창고|
:인수확인;
|외주사|
:납품예정 통보;
|구매|
:입고요청;
|창고|
:입고요청접수;
|외주사|
:납품;
|창고|
:입고완료;
|품질|
:품질검사;
if(품질문제) then (문제발생)
  :품질이상통보;
  |구매|
  :품질이상확인 및 조정;
  if(인수거부) then (인수거부)
    :입고취소요청;
    |창고|
    :입고취소접수;
    :출고;
    |구매|
    :구매취소;
    :재발주;
    stop
  else (인수)

  endif
else (문제없음)

endif
|구매|
:구매완료;
stop

legend bottom
  품질에서 자격미달인 품목을 폐기할 수 있는 단계를 추가해야 함
endlegend
@enduml
