@startuml
|고객사|
start
:견적요청;
|영업|
:견적요청접수;
:품목작성 및 BOM 구성;
:견적작성;
|고객사|
:견적수령;
:발주;
|영업|
:발주수령;
if (신규품목) then (품목확정 필요)
  :금형/목형 제작요청;
  |제작사|
  :제작;
  :납품;
  |생산|
  :샘플제작;
  |영업|
  :품목확정;
endif
:자재확보계획수립[+];
:생산요청;
|생산|
:생산요청접수;
:생산계획 배정 및 조정;
|생산|
:작업지시;
fork
  :출고요청;
  |창고|
  :출고요청접수;
  :출고;
fork again
  |생산|
  :검수요청;
  |품질|
  :검수요청접수;
endfork
|생산|
:작업진행;
:작업완료;
fork
  :입고요청;
  |창고|
  :입고요청접수;
  :입고;
fork again
  |품질|
  :품질검사;
  if(품질문제) then (문제발생)
    :품질이상통보;
    |생산|
    :품질이상확인 및 조정;
  else (문제없음)

  endif
endfork
|생산|
:생산완료 통보;
|품질|
|영업|
:납품요청;
|창고|
:배차;
:출고;
|고객사|
:인수;
|창고|
:납품완료;
detach

stop
legend bottom
  생산중 품질 이상시 처리 방안은 회의를 통해서 확인이 필요함
endlegend
@enduml
