@startuml
|고객사|
start
:견적요청;
|영업|
:견적요청접수;
:품목작성 및 BOM 구성;
:견적작성;
|고객사|
:견적수령;
:발주;
|영업|
:발주수령;
if (신규품목) then (품목확정 필요)
  :금형/목형 제작요청;
  |제작사|
  :제작;
  :납품;
  |생산|
  :샘플제작;
  |영업|
  :품목확정;
endif
:생산요청;
|생산|
:생산요청접수;
detach
|생산|
:구매요청;
|구매|
:구매요청접수;
:발주;
note right
  외주자재의 경우 창고에 출고 요청함
end note
|구매|
:입고요청;
note right
  검수 대상의 경우 입고요청시에 검수요청이 발생
end note
|창고|
:입고요청접수;
|창고|
:입고완료;
|품질|
:품질검사;
:검수완료;
|구매|
:구매완료;
note right
  해당 내용은 정산으로 진행되며 구매요청자에게 구매완료가 통보
end note
detach
|생산|
:생산완료 통보;
|영업|
:출하요청;
|창고|
:출하접수;
:배차;
:출고;
|고객사|
:인수;
|창고|
:출하완료;
detach
|영업|
:계산서발행;
|고객사|
:입금;
|영업|
:판매등록;
stop


@enduml
