@startuml
|영업|
start
:생산요청 전단계(1차와 동일);
:자재확보계획수립;
note left
  부자재에 대한 생산요청 또는 구매요청이 계획 및 진행되어
  생산 가능 시기가 결정된 후 생산 요청이 진행된다
end note
:생산요청;
|생산|
:생산요청접수;
:생산계획 배정 및 조정;
|생산|
:작업지시;
fork
  :출고요청;
  |창고|
  :출고요청접수;
  :출고;
fork again
  |생산|
  :검수요청;
  |품질|
  :검수요청접수;
endfork
|생산|
:작업시작;
fork
  |생산|
  :작업진행;
fork again
  |품질|
  :품질검사;
  if(품질문제) then (문제발생)
    :품질이상통보;
    |생산|
    :품질이상확인 및 조정;
  else (문제없음)

  endif
endfork
|생산|
:입고요청;
|창고|
:입고요청접수;
:입고;
detach
|생산|
:작업완료;
|생산|
:생산완료 통보;
detach
|영업|
:출하요청 후단계(1차와 동일);
stop
legend bottom
  작업시작 과 작업완료 단계는 반복됩니다.
endlegend
@enduml
