@startuml

title 공정 작업 흐름

legend
  공정은 인쇄, 톰슨, 성형등 모든 작업을 의미한다
endlegend

actor "작업 관리자"

actor "작업장"

entity "입출고 시스템"

"작업 관리자" -> "작업 관리자" : 작업 계획

"작업 관리자" -> "작업장" : 작업 계획 통보
note left
  작업 계획에는 계획에 해당하는 총 자재가 표기 되며 시간당 소요 자재를 지정한다
end note

"작업장" -> "작업장" : 작업 진행

loop 작업 완료 까지

  "작업장" -> "입출고 시스템" : 출고요청(자재)
  note left
    작업 계획에 정의된 시간당 소요 자재 만큼 분할하여 요청
  end note

  "입출고 시스템" -> "작업장" : 출고
  note left
    입고 내역서가 작업장에게 전달 된다
    입고 내역서에는 입고된 팔레트와 팔레트의에 존재하는 품목과 수량이 표시된다.
  end note

  "작업 관리자" -> "작업 관리자" : 입고확인
  note left
    작업 관리자가 입고내역을 패드에서 확인하고
    입고된 팔레트의 NFC 태그를 태그하여 내역을 확인한 후 입고확인을 진행한다.
  end note

  alt 입고 팔레트 불일치
    "작업장" -> "입출고 시스템" : 입고 확인 실패 통보
    note left
      불일치하는 파레트 정보가 입출고 시스템으로 전송된다.
    end note
    "입출고 시스템" -> "작업장" : 재출고
  end

  alt 문제 발생
    "작업장" -> "작업 관리자" : 문제 발생 통보
    alt 현재 해결 가능
      "작업 관리자" -> "작업 관리자" : 문제 해결
    else 현재 해결 불가능
      break 작업중단
      end
    end
  end

  alt 출고품 팔렛트 목표 수량 적재 완료
    "작업장" -> "입출고 시스템" : 출고 대상 등록
    note right
      작업자는 작업장에 배치된 출고 요청 NFC 태그를 태깅한후
      작업 진행중인 품목중 작업한 품목을 선택하고 수량을 입력하고 출고 요청
    end note
  end
end

"작업장" -> "작업 관리자" : 작업 완료 통보

"작업 관리자" -> "작업 관리자" : 작업 완료 확인
note left
  작업으로 발생된 출고품의 팔레트 확인
end note

"작업 관리자" -> "입출고 시스템" : 자재 출고요청
note left
  사용후 남은 자재의 수량 확인후 NFC 태그를 태깅하여
  작업 진행중인 품목중 자재 품목을 선택하여 수량을 입력하고 출고 대상 요청
end note





@enduml
