@startuml

actor 발주사

발주사->사무실 : 발주 요청

alt 기존 발주 품목
else 신규/수정 발주 품목
  사무실->사무실 : 품목 생성
end

사무실->사무실 : 품목 확정

사무실->공장 : 작업지시

공장->공장 : 생산 계획 할당

공장->"작업[인쇄]" : 진행 시작

"작업[인쇄]"->"작업[인쇄]" : 진행 및 진행 완료

"작업[인쇄]"->"작업[출력]" : 선행 작업 진행 완료 알림

"작업[출력]"->"작업[출력]" : 진행 및 진행 완료

"작업[출력]"->"공장" : 최종 진행 완료 알림

"공장"->"공장" : 작업 확인 또는 후처리 진행

"공장"->"사무실" : 작업지시 완료

"사무실"->"사무실" : 납품 처리(납품 처리지시 등등)


legend right
  품목 확정 : 품목의 정보 와 생산 준비가 완료된 상태
  기타 : 작업 의 사이에는 구역을 둬서 자재 및 완성물을 지게차로 이동할 수 있도록 해야 함
  추가 정의 : 발주를 통해 생성된 품목은 1:1 로 납품이 되지 않고 분할 및 통합 납품을 하게 된다
endlegend



@enduml
