@startuml

title 입출고 관리 - 출고

legend
  가변수량 허용은 작업/납품에 따라 출고 요청 수량과 정확히 일치하도록 하는 옵션
  출고지는 외부/내부 으로 선택
  출고 완료후에 팔레트가 있던 위치가 사용가능해 지며 그 전에는 임시로 사용이 불가능 하다.
endlegend

actor "출고 요청자"

actor "입출고 관리자"

actor "작업자"

entity "출고지"

"출고 요청자" -> "입출고 관리자" : 출고 요청
note left
  출고 요청서는 아래와 같이 구성된다
  - 품목/수량 목록
  - 출고지
    - 외부 - 업체 납품/외주 공정
    - 내부 - 작업 자재 전달
  - 출고요청일시
end note

"입출고 관리자" -> "입출고 관리자" : 출고 품목의 팔레트 선정
note left
  가변수량 허용에 따라 팔레트에 존재하는 품목의 수량이 정확히 일치 되도록 해야 한다.
end note

alt 외부 출고
  "입출고 관리자" -> "입출고 관리자" : 운송 선택
  note right
    운송 선택은 운송 사업자를 선택하거나 하지 않음을 의미
  end note
  "입출고 관리자" -> "작업자" : 인수증 발급

end

"입출고 관리자" -> "작업자" : 출고 지시
note right
  출고 지시서는 아래와 같이 구성 된다
  - 팔레트(품목*수량) / 팔레트 위치 목록
  - 출고지
  - 출고요청일시
end note

loop 출고 지시 팔레트 목록 모두 출고
  "작업자" -> "출고지" : 출고
  note right
    출고 팔레트 NFC 태깅하여 선택
    출고지 NFC 태그를 태깅하여 출고 처리
  end note
end

alt 외부 출고
  "작업자" -> "입출고 관리자" : 출고 완료 통보
  "입출고 관리자" -> "입출고 관리자" : 출고 완료
  ...외부에서 인수 확인 완료...
  "입출고 관리자" -> "입출고 관리자" : 인수증 확인 수령 및 운송 금액 입력
  note right
    메일이나 FAX로 수령한 환인된 인수증은 내용을 출력하여 사진촬영하여 시스템에 업로드
  end note
else 내부 출고
   alt 출고 확인 완료
    "출고 요청자" -> "입출고 관리자" : 출고 확인
    "입출고 관리자" -> "입출고 관리자" : 출고 완료
   else 출고 확인 실패
    "출고 요청자" -> "입출고 관리자" : 출고 확인 실패 통보
    "입출고 관리자" -> "작업자" : 회수 통보
    note right
      불일치 팔레트 회수 후 기존 위치로 복원
      입출고 관리자가 필요에 따라 수동 출고를 진행
    end note
   end
end

@enduml
